export const unitList = [
  { value: "g" },
  { value: "kg" },
  { value: "mL" },
  { value: "L" },
  { value: "大さじ" },
  { value: "小さじ" },
  { value: "カップ" },
  { value: "個" },
  { value: "本" },
  { value: "枚" },
  { value: "袋" },
  { value: "丁" },
  { value: "片" },
  { value: "適量" },
  { value: "少々" },
  { value: "その他" },
]
